(function(){var c={id:"75554c740f0d34260e13c52d8c748a8b"};var h=!0,k=null,l=!1,m;function n(a){return!a?k:"string"==typeof a||a instanceof String?document.getElementById(a):a.nodeName&&(1==a.nodeType||9==a.nodeType)?a:k}function q(a){a=n(a);return 9==a.nodeType?a:a.ownerDocument||a.document}function r(a,d){return"[object "+d+"]"==={}.toString.call(a)}function s(a){return"[object String]"==Object.prototype.toString.call(a)?document.getElementById(a):a}
function t(a,d){a=s(a);var b=q(a);return b.defaultView&&b.defaultView.getComputedStyle&&(b=b.defaultView.getComputedStyle(a,k))?b[d]||b.getPropertyValue(d):""}var u=u||{},v=v||[];v.filter=function(a,d,b){for(var e=0,f;f=v[e];e++)if(f=f[b])d=f(a,d);return d};function aa(a){return 0>a.indexOf("-")&&0>a.indexOf("_")?a:a.replace(/[-_][^-_]/g,function(a){return a.charAt(1).toUpperCase()})}
function w(a,d){a=n(a);d=aa(d);var b=a.style[d]||(a.currentStyle?a.currentStyle[d]:"")||t(a,d);if(!b||"auto"==b){var e=u[d];e&&(b=e.get?e.get(a,d,b):w(a,e))}if(e=v)b=e.filter(d,b,"get");return b}
var x=/msie (\d+\.\d+)/i.test(navigator.userAgent),y=/webkit/i.test(navigator.userAgent),ba=/gecko/i.test(navigator.userAgent)&&!/like gecko/i.test(navigator.userAgent),z="CSS1Compat"==document.compatMode,ca=navigator.cookieEnabled,da=navigator.javaEnabled(),ea=navigator.language||navigator.browserLanguage||navigator.s||navigator.t||"",fa=window.screen.width+"x"+window.screen.height,ga=window.screen.colorDepth;
function A(a){a=n(a);var d=q(a);0<ba&&d.getBoxObjectFor&&w(a,"position");var b={left:0,top:0},e;if(a==(x&&!z?d.body:d.documentElement))return b;if(a.getBoundingClientRect)a=a.getBoundingClientRect(),b.left=Math.floor(a.left)+Math.max(d.documentElement.scrollLeft,d.body.scrollLeft),b.top=Math.floor(a.top)+Math.max(d.documentElement.scrollTop,d.body.scrollTop),b.left-=d.documentElement.clientLeft,b.top-=d.documentElement.clientTop,a=d.body,d=parseInt(w(a,"borderLeftWidth")),a=parseInt(w(a,"borderTopWidth")),
x&&!z&&(b.left-=isNaN(d)?2:d,b.top-=isNaN(a)?2:a);else{e=a;do{b.left+=e.offsetLeft;b.top+=e.offsetTop;if(0<y&&"fixed"==w(e,"position")){b.left+=d.body.scrollLeft;b.top+=d.body.scrollTop;break}e=e.offsetParent}while(e&&e!=a);0<y&&"absolute"==w(a,"position")&&(b.top-=d.body.offsetTop);for(e=a.offsetParent;e&&e!=d.body;)b.left-=e.scrollLeft,b.top-=e.scrollTop,e=e.offsetParent}return b}
function B(a,d){var b=2<arguments.length?[].slice.call(arguments,2):k;return function(){var e="[object String]"==Object.prototype.toString.call(a)?d[a]:a,f=b?b.concat([].slice.call(arguments,0)):arguments;return e.apply(d||e,f)}}var C=C||[];function D(a,d,b){function e(d){b.call(a,d)}d=d.replace(/^on/i,"");a=s(a);var f,g=d;d=d.toLowerCase();E&&E[d]&&(f=E[d](a,d,e),g=f.type,e=f.k);a.addEventListener?a.addEventListener(g,e,l):a.attachEvent&&a.attachEvent("on"+g,e);C[C.length]=[a,d,b,e,g]}
function G(a,d,b){a=s(a);d=d.replace(/^on/i,"").toLowerCase();for(var e=C.length,f=!b,g,p;e--;)if(g=C[e],g[1]===d&&g[0]===a&&(f||g[2]===b))p=g[4],g=g[3],a.removeEventListener?a.removeEventListener(p,g,l):a.detachEvent&&a.detachEvent("on"+p,g),C.splice(e,1)}var E=E||{};E.g=function(a,d){var b=d.relatedTarget,e=d.currentTarget,f;if(!(f=b===l))if(!(f=e==b))if(f=b)if(!(f="xul"==b.prefix))f=s(e),b=s(b),f=f.contains?f!=b&&f.contains(b):!!(f.compareDocumentPosition(b)&16);if(!f)return a.call(e,d)};
E.mouseenter=window.attachEvent?k:function(a,d,b){return{type:"mouseover",k:B(E.g,this,b)}};E.mouseleave=window.attachEvent?k:function(a,d,b){return{type:"mouseout",k:B(E.g,this,b)}};function H(a,d){var b=new Image,e="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[e]=b;b.onload=b.onerror=b.onabort=function(){b.onload=b.onerror=b.onabort=k;b=window[e]=k;d&&d(a)};b.src=a}function I(a,d){if(window.sessionStorage)try{window.sessionStorage.setItem(a,d)}catch(b){}}
(m=function(){function a(){if(!a.e){a.e=h;for(var b=0,d=e.length;b<d;b++)e[b]()}}function d(){try{document.documentElement.doScroll("left")}catch(b){setTimeout(d,1);return}a()}var b=l,e=[],f;document.addEventListener?f=function(){document.removeEventListener("DOMContentLoaded",f,l);a()}:document.attachEvent&&(f=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",f),a())});(function(){if(!b)if(b=h,"complete"===document.readyState)a.e=h;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",
f,l),window.addEventListener("load",a,l);else if(document.attachEvent){document.attachEvent("onreadystatechange",f);window.attachEvent("onload",a);var e=l;try{e=window.frameElement==k}catch(p){}document.documentElement.doScroll&&e&&d()}})();return function(b){a.e?b():e.push(b)}}()).e=l;var J="https:"===document.location.protocol?"https:":"http:",K="ai ck cl ds et ep fl ja ln rnd su v".split(" "),L={},M=[],N=l;
function ha(){for(var a=[],d=0,b=K.length;d<b;d++){var e=K[d],f=L[e];"undefined"!==typeof f&&""!==f&&a.push(e+"="+encodeURIComponent(""+f))}return a.join("&")}function O(){L.rnd=Math.round(2147483647*Math.random());var a=J+"//click.hm.baidu.com/mkt.gif?"+ha();P.add(a);H(a,function(){P.remove(a)})}
function Q(a){var d=[];d.push("ai="+c.id);d.push("n="+encodeURIComponent(a.name));d.push("m="+encodeURIComponent(a.message));d.push("r="+encodeURIComponent(document.referrer));d.push("rnd="+Math.round(2147483647*Math.random()));H(J+"//click.hm.baidu.com/mkt.gif?"+d.join("&"))}
var P=function(){function a(a){var e=(window.sessionStorage?window.sessionStorage.getItem(d):k)||"";e&&(a=encodeURIComponent(a.replace(/^https?:\/\//,"")).replace(/([\*\(\)])/g,"\\$1"),(e=e.replace(RegExp(a+",?","g"),"").replace(/,$/,""))?I(d,e):window.sessionStorage&&window.sessionStorage.removeItem(d))}var d="Mkt_unsent_"+c.id;return{add:function(a){var e=(window.sessionStorage?window.sessionStorage.getItem(d):k)||"",e=encodeURIComponent(a.replace(/^https?:\/\//,""))+(e?","+e:"");I(d,e)},remove:a,
q:function(){var b=window.sessionStorage?window.sessionStorage.getItem(d):k;if(b)for(var b=b.split(","),e=0,f=b.length;e<f;e++)H(J+"//"+decodeURIComponent(b[e]),function(b){a(b)})}}}(),R=function(){var a;return{init:function(){if(!a){var d=n("_bdhm_mkt_"+c.id);if(!d)return l;var b=/^script|style$/i;for(a=d.previousSibling;a&&(1!==a.nodeType||b.test(a.tagName));)a=a.previousSibling}return!!a},n:function(){return A(a)},o:function(){if(!a)return l;try{var d=A(a).top,b=a.offsetHeight;if(0>=b&&(b=t(a,
"elemHeight"),0>b||b==k))b=w(a,"elemHeight");var b=parseFloat(b)||0,e=window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop,f=("BackCompat"===document.compatMode?document.body:document.documentElement).clientHeight,d=d+0.5*b;return d>e&&d<e+f}catch(g){return Q(g),l}},d:function(){return a}}}(),S=function(){function a(){for(var a=R.o(),e=d.length-1;0<=e;e--)a?d[e].a():d[e].b()}var d=[];D(window,"scroll",a);D(window,"resize",a);return{j:a,l:function(a){d.push(a)}}}(),ia=function(){var a=
l,d=0,b=l;return{a:function(){!a&&!b&&(b=h,d=setTimeout(function(){a=h;L.et=1;L.ep="";O();b=l},1E3))},b:function(){!a&&b&&(clearTimeout(d),b=l)}}}();function T(a){this.m=a;this.i=this.c=this.h=0}T.prototype={a:function(){this.c||this.i++;this.c||(this.c=+new Date)},b:function(){this.h=U(this);this.c=0}};function U(a){var d=a.h;if(a.c){var b=+new Date-a.c;b>=a.m&&(d+=b)}return d}
function V(){function a(){var b=R.d(),e=h;try{if(!b||!b.parentNode||11==b.parentNode.nodeType||N==h)e=l}catch(f){e=l}e?setTimeout(a,100):(G(window,"unload",d),d())}function d(){L.et=2;L.ep=[U(f),U(g),U(Z),U(F),U(p)].join("*");O();L.et=3;for(var a="",b=0;10>b;b++)var d=M[b],a=a+(d?d.i+"*"+U(d)+"!":"*!");L.ep=a.replace(/(\*\!)+$/,"").replace(/\!$/,"");L.ep&&O()}function b(a){a=a||window.event;a.target&&a.target!==window||("focus"===a.type||"focusin"===a.type?(F.a(),S.j()):(F.b(),f.b(),setTimeout(function(){g.b();
p.b()},200)),G(document.body,"mousemove",e))}function e(){F.a();G(document.body,"mousemove",e);S.j()}S.l(ia);var f=new T(1E3);S.l(f);var g=new T(100);D(R.d(),"mousemove",function(){g.a()});D(R.d(),"mouseenter",function(){g.a()});D(R.d(),"mouseleave",function(){g.b()});var p=new T(100);D(document.body,"mousemove",function(){p.a()});D(document.body,"mouseenter",function(){p.a()});D(document.body,"mouseleave",function(){p.b()});var F=new T(1E3);D(document.body,"mousemove",e);"object"===typeof document.onfocusin?
(D(document,"focusin",b),D(document,"focusout",b)):(D(window,"focus",b),D(window,"blur",b));var Z=new T(0);Z.a();D(R.d(),"mousedown",function(a){var b=R.n(),d;if(x){var e=Math.max(document.documentElement.scrollTop,document.body.scrollTop);d=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft);d=a.clientX+d;a=a.clientY+e}else d=a.pageX,a=a.pageY;d-=b.left;b=a-b.top;L.et=4;L.ep=d+"*"+b;O()});D(window,"unload",d);a()}
var W={init:function(){var a=window._mkt;if(a&&a.length)for(var d=0,b=a.length;d<b;d++)W.push(a[d]);window._mkt=W.p},p:{push:function(){W.push.apply(W,arguments)}},push:function(a){if(W.r(a)&&r(W[a[0]],"Function"))W[a[0]](a.slice(1))},r:function(a){if(!r(a,"Array"))return l;for(var d=a.length-1;0<=d;d--){var b=a[d];if(!r(b,"String")&&!r(b,"Number")&&!r(b,"Boolean"))return l}return h},f:function(a,d){a=a||[1];for(var b=0,e=a.length;b<e;b++)if(0<a[b]&&11>a[b]){var f=a[b]-1;M[f]=M[f]||new T(0);d(M[f])}},
_startTimer:function(a){W.f(a,function(a){a.a()})},_pauseTimer:function(a){W.f(a,function(a){a.b()})},_continueTimer:function(a){W.f(a,function(a){a.c||(a.c=+new Date)})},_stopTimer:function(a){0<a.length?W.f(a,function(a){a.b()}):N=h}};
try{L.ai=c.id;L.su=document.referrer;L.ds=fa;L.cl=ga+"-bit";L.ln=ea;L.ja=da?1:0;L.ck=ca?1:0;var X="";if(navigator.plugins&&navigator.mimeTypes.length){var Y=navigator.plugins["Shockwave Flash"];Y&&Y.description&&(X=Y.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{var $=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");$&&(X=$.GetVariable("$version"))&&(X=X.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(ja){}L.fl=X;L.v="1.0.58";P.q();L.et=0;L.ep="";O();W.init();R.init()?
V():m(function(){R.init()&&V()})}catch(ka){Q(ka)};})();
